export const tempStories =[
    { "id":1,
      "title":"Animal Sounds",
      "createdAt":"2020-11-19T12:40:38.534Z",
      "updatedAt":"2020-11-19T12:40:38.534Z",
      "categoryId":1,
      "pages": [
        { "id":1,
        "content":"Hi [ name child], this is [ name sender ] and today I’m going to teach you about animals and what sounds they make. \n        I’d rather be with you today so we can practice together, but this way you get practice them and tell me about your favourite animal sound next time we chat! \n        Here comes the first one: \n        “assignment: record yourself pretending to be a monkey. Make huhuhuhu sounds” \n        Can you guess which one I did? \n        Great job [ name child]! That was a monkey!",
          "image":"https://raw.githubusercontent.com/ProjectLolo/ProjectLoLoStories/a366207126da4a92dff47e75d971fbafa187b7cb/App/assets/images/0.001monkey.svg",
          "storyId":1,
            "createdAt":"2020-11-19T12:40:38.569Z",
            "updatedAt":"2020-11-19T12:40:38.569Z"
          },
        { "id":2,
        "content":"Now [ name sender ] is going to try another one. Let’s see. \n        This one is a scary one. It has stripes all over its body. How about this one: \n        “assignment: record yourself pretending to be a tiger. Make rawwwww sounds”\n        Great job [ name child]! That was a tiger!",
          "image":"",
          "storyId":1,
            "createdAt":"2020-11-19T12:40:38.569Z",
            "updatedAt":"2020-11-19T12:40:38.569Z"
          },
        { "id":3,
          "content":"Now [ name sender ] is going to try a last one. \n        I’d like a cute and cuddly one because I just love cuddling with you [ name child]!\n        “assignment: record yourself pretending to be a puppy/dog. Make cute woef woef sounds” Great job [ name child]! That was a puppy!",
          "image":"https://raw.githubusercontent.com/ProjectLolo/ProjectLoLoStories/9d84dd4599094fc4cdfc3c38c2f36b3137ee4bdd/App/assets/images/0.001_dog_puppy.svg",
          "storyId":1,
            "createdAt":"2020-11-19T12:40:38.569Z",
            "updatedAt":"2020-11-19T12:40:38.569Z"},
        { "id":4,
          "content":"Now I’d like to tell you about [ name sender ]’s favourite animal. \n        My favourite animal is the [ assignment: add animal ] \n        Because [ assignment: add animal ]\n        [ optional assignment: room to personalize/add a story about that animal ]  That was all for today, [ name sender ] is off!\n        Next time I see you can you tell me about your favourite animal? \n        Bye bye [ name child]! Know that I’m always here for you!", 
          "image":"", "storyId":1, 
          "createdAt":"2020-11-19T12:40:38.569Z", 
          "updatedAt":"2020-11-19T12:40:38.569Z"}]
        },
    { "id":2,
      "title":"Nickname", 
      "createdAt":"2020-11-19T12:40:38.534Z", 
      "updatedAt":"2020-11-19T12:40:38.534Z", 
      "categoryId":2, 
      "pages": [
        { "id":5,
        "content":"Hi [ name child], this is [ name sender ] and today I’m going to come up with a cool nickname. \n        I’d rather be with you today so we can come up with fun names together, but this way you can think about the names I came up with and let me know which one you like best next time we chat! Here comes the first one: \n        “assignment: record yourself pretending to be a pig/babe” \n        Can you guess which one I did? \n        Great job [ name child]! That was a babe! Do you like babe as a nickname for me?", 
        "image":"https://raw.githubusercontent.com/ProjectLolo/ProjectLoLoStories/a366207126da4a92dff47e75d971fbafa187b7cb/App/assets/images/0.002NicknameBabe.svg", 
        "storyId":2, 
        "createdAt":"2020-11-19T12:40:38.569Z", 
        "updatedAt":"2020-11-19T12:40:38.569Z"}, 
        { "id":6, 
          "content":"Now [ name sender ] is going to try another one. Let’s see. \n        This one is really yummy. I love eating it. How about “cutie pie”?: \n        “assignment: record yourself saying nom nom nom” pretending to eat a pie", 
          "image":"", 
          "storyId":2, 
          "createdAt":"2020-11-19T12:40:38.569Z", 
          "updatedAt":"2020-11-19T12:40:38.569Z"}, 
        { "id":7, 
          "content":"Now [ name sender ] is going to try a last one. \n        This one is quite sweet, maybe a bit too sweet for my taste [ name child]!\n        “assignment: pretend to be a princess and wave your royal hand”\n        Great job [ name child]! I was a princess!\n        \n        Now I’d like to tell you about [ name sender ]’s preferred nickname \n        My favourite nickname is [ assignment: add nickname ] \n        Because [ add reason for your nickname ]\n        [ optional assignment: room to personalize/add a story about your nickname ]  \n        That was all for today, [ name sender ] is off!\n        Next time I see you can you tell me about your nickname? \n        Bye bye [ name child]! [ your nickname ] is off! ", 
          "image":"", 
          "storyId":2, 
          "createdAt":"2020-11-19T12:40:38.569Z", 
          "updatedAt":"2020-11-19T12:40:38.569Z"}],
    }, 
    { "id": 3,
      "title":"Baby goes to bed", 
      "createdAt":"2020-11-19T12:40:38.534Z", 
      "updatedAt":"2020-11-19T12:40:38.534Z", 
      "categoryId":1, 
      "pages": [
        {
          "id": 8,
          "content":"This is a bedtime story, read to you by [ name sender ] \n        [ Name sender ] would rather be close to [ name child] , \n        but this way [ name sender ]  can still read to [ name child ]  while being apart and that is great, \n        [ Add “jaaaaaj” sound when flipping page ]",
          "image":"https://github.com/ProjectLolo/ProjectLoLoStories/blob/development/App/assets/images/Illustratie1_Tekengebied%201.png?raw=true",
          "storyId":3, 
          "createdAt":"2020-11-19T12:40:38.569Z", 
          "updatedAt":"2020-11-19T12:40:38.569Z",
        },
        {
          "id":2,
          "content": "This is a bottle of milk,\n        yummy! So nice!\n        [ Name child ]  drinks the bottle until it’s empty\n        [ add drinking sound “glu glu glu” when flipping page]  ",
          "image":"https://github.com/ProjectLolo/ProjectLoLoStories/blob/development/App/assets/images/Illustratie2_Tekengebied%201.png?raw=true",
          "storyId":3, 
          "createdAt":"2020-11-19T12:40:38.569Z", 
          "updatedAt":"2020-11-19T12:40:38.569Z",
        },
        {
          "id":3,
          "content": "This is [ Name child ] in a pram,\n        [ Name child ]  loves going for walks outside\n        Can you hear the birds whistle?\n        [ add bird sound/whistle when flipping page]  ",
          "image":"https://github.com/ProjectLolo/ProjectLoLoStories/blob/development/App/assets/images/Illustratie3_Tekengebied%201.png?raw=true",
          "storyId":3, 
          "createdAt":"2020-11-19T12:40:38.569Z", 
          "updatedAt":"2020-11-19T12:40:38.569Z",
        },
        {
          "id":4,
          "content": "This is one of my favourite toys,\n        [ Name child ]  can play with it and watch the stars,\n        they are twinkling in the sky\n        [ add twinkle sound “twinkly twinkly twinkly” when flipping page]  ",
          "image":"https://github.com/ProjectLolo/ProjectLoLoStories/blob/development/App/assets/images/Illustratie4_Tekengebied%201.png?raw=true",
          "storyId":3, 
          "createdAt":"2020-11-19T12:40:38.569Z", 
          "updatedAt":"2020-11-19T12:40:38.569Z",
        },
        {
          "id":5,
          "content": "After a long day [ Name child ]  goes to bath,\n        It’s fun to play with the bubbles and splash with the water\n        [ add bubble sound “blub blub blub” when flipping page ]  ",
          "image":"https://github.com/ProjectLolo/ProjectLoLoStories/blob/development/App/assets/images/Illustratie5_Tekengebied%201.png?raw=true",
          "storyId":3, 
          "createdAt":"2020-11-19T12:40:38.569Z", 
          "updatedAt":"2020-11-19T12:40:38.569Z",
        },
        {
          "id":6,
          "content": "Now [ Name child ]  is clean and can go to bed,\n        the bedtime story is almost finished,\n        [ add shhhhhhh sound when flipping page]  ",
          "image":"https://github.com/ProjectLolo/ProjectLoLoStories/blob/development/App/assets/images/Illustratie6_Tekengebied%201.png?raw=true",
          "storyId":3, 
          "createdAt":"2020-11-19T12:40:38.569Z", 
          "updatedAt":"2020-11-19T12:40:38.569Z",
        },
        {
          "id":7,
          "content": "Close your eyes sweet [ Name child ]  and dream beautiful dreams,\n        know you are safe and know that you’re loved",
          "image":"https://github.com/ProjectLolo/ProjectLoLoStories/blob/development/App/assets/images/Illustratie7_Tekengebied%201.png?raw=true",
          "storyId":3, 
          "createdAt":"2020-11-19T12:40:38.569Z", 
          "updatedAt":"2020-11-19T12:40:38.569Z",
        },
          
      ]
    }
    
]
    